# build
# utilisation d'une image node alpine pour construire l'application
FROM node:18-alpine AS build
# définition du répertoire de travail dans le conteneur
WORKDIR /app
# copie des fichiers de configuration et d'installation des dépendances
COPY package*.json ./
# installation des dépendances nécessaires pour le build
RUN npm install
# copie du code source de l'application dans le conteneur
COPY . .
# lance la commande de build
RUN npm run build

# serveur de production
# utilisation de nginx pour servir les fichiers statiques générés par le build
FROM nginx:stable-alpine AS production
# copie des fichiers de build dans le dossier de nginx
COPY --from=build /app/dist /usr/share/nginx/html
# expose le port 80 pour le trafic HTTP
EXPOSE 80
# commande pour démarrer nginx en mode premier plan
CMD ["nginx", "-g", "daemon off;"]