# automatisation (github actions)
name: "CI - Space Invaders"

# trigger : a quel moment lusine se met en marche
# on push : quand il recoit un nouveau push sur github
on:
  push:
    branches: ["**"]
    paths:
      - "games/Space_Invaders/**"
  pull_request:
      branches: ["**"]
      paths:
        - "games/Space_Invaders/**"
  # permet de lancer lusine sans push
  workflow_dispatch:

# liste les automatisations
jobs:
  build-lint-test:
    # precise a github que cest une version ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: games/Space_Invaders
    # etape d automatisation
    steps:
      # recupere le code depuis github pour le mettre en local
      - name: Checkout Code
        uses: actions/checkout@v4

        # install de node js (version 18 pour le jeu space invaders)
      - name: Install Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: games/Space_Invaders/package-lock.json

      # install des dépendances
      - name: Install Dependencies
        run: npm install

        # vulnérabilité DevSecOps
      - name: Security Audit
        # npm audit: scanner natif a node js, compare a une liste de failles
        # --audit: filtre qui sert a ignorer les alertes mineures mais bloque sil y a des erreurs plus fortes
        run: npm audit --audit-level=critical || true

        # permet de conventionnalisé lecriture du code de la meme maniere
      - name: Linter
        run: npx eslint src/**/*.js

        # test unitaire WARNING a finir
      - name: Run Unit Tests
        run: npm test

        # compilation
      - name: Build Projects
        run: npm run build

        # message en cas de test/compilation réussit
      - name: Final Status
        if: success()
        run: echo "Build, lint and tests succesful for Space Invaders"

        # message en cas de test/Compilation raté
      - name: Failed Status
        if: failure()
        run: echo "Build, lint or tests failed for Space Invaders"