name: "CI - Two-ships"

on:
  push:
    branches: ["**"]
    # paths: 
    #  - "games/Two_Ships_Passing_In_The_Night/**"
  pull_request:
    branches: ["**"]
    # paths: 
    #  - "games/Two_Ships_Passing_In_The_Night/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: games/Two_Ships_Passing_In_The_Night

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: games/Two_Ships_Passing_In_The_Night/package-lock.json
      - run: npm install --no-audit --no-fund --loglevel error

  audit:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: games/Two_Ships_Passing_In_The_Night/package-lock.json
      - run: |
          echo "### 🛡️ Rapport de Sécurité" >> $GITHUB_STEP_SUMMARY
          npm audit --audit-level=critical || echo "Des failles critiques ont été trouvées" >> $GITHUB_STEP_SUMMARY

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: games/Two_Ships_Passing_In_The_Night/package-lock.json
      - run: npm install
      - run: npm run lint

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: games/Two_Ships_Passing_In_The_Night/package-lock.json
      - run: npm install
      - run: npm test

  
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: games/Two_Ships_Passing_In_The_Night/package-lock.json
      - run: npm install
      - run: npm run build